# Generated by Django 3.2.18 on 2023-04-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
